# Site settings
title: CI and CD with GitHub
description: Jgois demo blog
email: mail.jgois@gmail,com
twitter_username: jg0is
github_username:  jgois
baseurl:
url: https://jgois-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
